### ISSUE TITLE
WinFsp and Cirrus CI

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#289]
## Question

Hi,

Have you ever tried to run WinFsp on Cirrus CI, in a Windows container ?
Does it work ?

I'm trying the following basic `.cirrus.yml` configuration :

```
task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  install_script:
    - choco install -y winfsp
    - choco install -y cyg-get
    - cyg-get cmake make gcc-g++ libssl-devel
    - C:\tools\cygwin\bin\bash.exe --login -c "cd /cygdrive/c/Program*/WinFsp/opt/cygfuse ; sh install.sh"
  script:
    - set CHERE_INVOKING=1
    - C:\tools\cygwin\bin\bash.exe --login -c "./build_my_fs.sh"
    - C:\tools\cygwin\bin\bash.exe --login -c "./mount_my_fs.sh"
    - C:\tools\cygwin\bin\bash.exe --login -c "ls -l /cygdrive/"
```

Everything runs fine, but FS does not mount.
Of course same procedure on another Windows machine (workstation, VM...) works perfectly.

I'm trying to debug, but of course it's quite difficult on such an environment, so if you have a clue...

Thank you very much 👍
